apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-site
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: brandon_homework.com # 請改成你的網域
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: static-site
            port:
              number: 80
