replicaCount: 1

image:
  repository: brandonwen1017/bito-homework:latest
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  host: brandon_homework.com
